alias vim='~/bin/vim'
alias vi='~/bin/vim'
alias v='~/bin/vim'
alias c='clear'
alias r='reset'
alias l='ls -lrt'
alias nanodegree='cd ~/proyectos/nanodegree;source activate carnd-term1'
alias wiki='cd ~/proyectos/wiki/;vim index.md'
alias vectorial='cd ~/proyectos/python/vectorial/;py_ide.sh'
#alias python=python3
#alias pip=pip3
alias sudo='sudo '
