set encoding=utf-8
call pathogen#infect()      " Executes the pathogen plugin, which loads other plugins
let mapleader=","           " Changes Leader key into a comma instead of a backslash

set nocompatible            " Prefents VIM from being nerfed into acting like VI
set viminfo='1000,f1,:1000,/1000
set history=500

vnoremap < <gv  " better indentation
vnoremap > >gv  " better indentation

set laststatus=0
syntax on                   " Enables syntax highlighting
set nu                      " Enable Line Numbers
set nowrap                  " Disable word wrap
set vb                      " Visual bell instead of beeps
set ruler                   " Displays cursor position on bottom right of screen
set bs=2		            " Backspace

set tabstop=4               " Columnas por tab
set softtabstop=4	    
set shiftwidth=4            " Columnas en el indentado
set expandtab               " No usar espacios en vez de tab

set hidden                  " Switch between unsaved buffers w/o needing to save, preserves history
filetype indent on          " Syntax Highlight
filetype plugin on          " Needed for snipMate
set autoindent              " Autoindent

"------  Searching  ------
set incsearch               " Search while typing
set ignorecase              " Case Insensitive Searching
set smartcase               " Lowercase = case insensitive, any uppercase = case sensitive
set hlsearch                " Highlight all search results

" http://www.vim.org/scripts/script.php?script_id=2572
noremap <leader>a :Ack 
noremap <leader>A <C-w>j<C-w>c<C-w>l
let g:ackprg="ack -H --nocolor --nogroup --column --type-add php=.tpl"

"------  Replacing ------
"type S, then type what you're looking for, a /, and what to replace it with
nmap S :%s//g<LEFT><LEFT>
vmap S :s//g<LEFT><LEFT>

"------  NERDTree Options  ------
let NERDTreeIgnore=['CVS','\.dSYM$']
let NERDTreeChDirMode=2     "setting root dir in NT also sets VIM's cd
nmap <silent> <Leader>d :NERDTreeToggle<CR>
" These prevent accidentally loading files while in the NERDTree panel
autocmd FileType nerdtree noremap <buffer> <c-left> <nop>
autocmd FileType nerdtree noremap <buffer> <c-h> <nop>
autocmd FileType nerdtree noremap <buffer> <c-right> <nop>
autocmd FileType nerdtree noremap <buffer> <c-l> <nop>
"autocmd vimenter * if !argc() | NERDTree | endif " Open NERDTree if we're simply launching vim
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif " close if only nerdtree open

"------  Tagbar Options  ------
" http://adamyoung.net/Exuberant-Ctags-OS-X
" http://www.vim.org/scripts/script.php?script_id=273
let g:tagbar_width=26
noremap <silent> <Leader>y :TagbarToggle<CR>

"------  Buffers  ------
" Ctrl Left & Right move between buffers
noremap <silent> <C-left> :bprev<CR>
noremap <silent> <C-h> :bprev<CR>
noremap <silent> <C-right> :bnext<CR>
noremap <silent> <C-l> :bnext<CR>
" Closes the current buffer
nnoremap <silent> <Leader>q :Bclose<CR>

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! %!sudo tee > /dev/null %

"------  Moving Between Windows  ------
nnoremap <Leader>h <C-w>h
nnoremap <Leader>l <C-w>l
nnoremap <Leader>j <C-w>j
nnoremap <Leader>k <C-w>k
nnoremap <Leader>wo <C-w>o
nnoremap <Leader>wv <C-w>v<C-w>l

" Opens an edit command with the path of the currently edited file filled in Normal mode: <Leader>ee
map <Leader>ee :e <C-R>=expand("%:p:h") . "/" <CR>

" Edit and Reload .vimrc files
nmap <silent> <Leader>ev :e $MYVIMRC<CR>
nmap <silent> <Leader>es :so $MYVIMRC<CR>

" When pressing <leader>cd switch to the directory of the open buffer
"map <Leader>cd :cd %:p:h<CR>
" ,ct = Builds ctags
map <Leader>ct :! /usr/local/bin/ctags -R *<CR>

" F2 = Paste Toggle (in insert mode, pasting indented text behavior changes)
set pastetoggle=<F2>
" ,T = Delete all Trailing space in file
map <Leader>T :%s/\s\+$//<CR>
" ,U = Deletes Unwanted empty lines
map <Leader>U :g/^$/d<CR>
" ,R = Converts tabs to spaces in document
map <Leader>R :retab<CR>
" ,p = Runs PHP lint checker on current file
map <Leader>p :! php -l %<CR>
" ,P = Runs PHP and executes the current file
map <Leader>P :! php -q %<CR>
" ,L = Toggle line numbers
map <Leader>L :set invnumber<CR>
" ,v = Paste
map <Leader>v "+gP
" ,c = Copy
map <Leader>c "+y

" Accidentally pressing Shift K will no longer open stupid man entry
noremap K <nop>

map <Leader>? :Helptags<CR>

set t_Co=256
"colorscheme hybrid
"colorscheme seoul256-light
colorscheme solarized           "This theme works great in 256 colors
set background=dark
set mouse=a                     "This allows mouse scrolling in terminal, and selection of text
set t_ut=

if filereadable($HOME.'/.vimrc_local')
    source $HOME/.vimrc_local
endif

" Agregados por mi
"
let localvimrc_ask=0
let g:fuf_enumeratingLimit = 60
let g:fuf_buffertag__php='--language-force=php --php-types=cdf'
nmap <silent> <Leader>b :FufBuffer<CR>
nmap <silent> <Leader>o :FufCoverageFile<CR>
nmap <silent> <Leader>t :FufBufferTag<CR>
nmap <silent> <Leader>m :Goyo<CR>

" Marcas en columna 80
highlight ColorColumn ctermbg=260 ctermfg=black
call matchadd('ColorColumn', '\%80v', 100)

"====[ Use persistent undo ]=================
set undofile
set undodir=$HOME/tmp/.vim_undo_files
set undolevels=5000

" Remove search highlight
nmap <DEL> :nohlsearch<CR>

map <S-F6> :exe  "write ".g:FtpSync_Proto."://".g:FtpUpdateServer."/".g:FtpUpdatePath.expand("%")<CR>
map <Leader>7 :exe  "write ".g:FtpSync_Proto."://".g:FtpUpdateServer."/".g:FtpUpdatePath.expand("%")<CR>

"
autocmd Filetype java set makeprg=javac\ %
set errorformat=%A%f:%l:\ %m,%-Z%p^,%-C%.%#
map <F9> :make<Return>:copen<Return>
map <F10> :cprevious<Return>
map <F11> :cnext<Return>

autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
autocmd FileType html setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType css setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType javascript setlocal ts=4 sts=4 sw=4 noexpandtab
autocmd BufNewFile,BufRead *.rss setfiletype xml

set clipboard=unnamed
nmap <silent> <Leader>s :setlocal spell spelllang=es_es<cr>

"let g:vimwiki_list = [{'path': '~/proyectos/personales/wiki/', 'path_html': '~/proyectos/personales/wiki_html/'}]
let g:vimwiki_ext2syntax = {'.md': 'markdown'}

"jedi
let g:jedi#goto_command = "<leader>g"
let g:jedi#usages_command = "<leader>n"
"let g:jedi#auto_initialization = 0
let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0

set foldmethod=indent
set foldnestmax=10
nnoremap <space> za
vnoremap <space> zf

" Disable swap and backup
set nobackup
set nowritebackup
set noswapfile
